version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    environment:
      DB_URL: ${DB_URL}
    ports:
      - ${API_PORT}:8000
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: flow
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
